// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PBMsgReqPve.proto

#ifndef PROTOBUF_PBMsgReqPve_2eproto__INCLUDED
#define PROTOBUF_PBMsgReqPve_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_PBMsgReqPve_2eproto();
void protobuf_AssignDesc_PBMsgReqPve_2eproto();
void protobuf_ShutdownFile_PBMsgReqPve_2eproto();

class PBMsgReqPve;

// ===================================================================

class PBMsgReqPve : public ::google::protobuf::Message {
 public:
  PBMsgReqPve();
  virtual ~PBMsgReqPve();

  PBMsgReqPve(const PBMsgReqPve& from);

  inline PBMsgReqPve& operator=(const PBMsgReqPve& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PBMsgReqPve& default_instance();

  void Swap(PBMsgReqPve* other);

  // implements Message ----------------------------------------------

  PBMsgReqPve* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PBMsgReqPve& from);
  void MergeFrom(const PBMsgReqPve& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 type = 1;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 1;
  inline ::google::protobuf::int32 type() const;
  inline void set_type(::google::protobuf::int32 value);

  // optional int32 knightId = 2;
  inline bool has_knightid() const;
  inline void clear_knightid();
  static const int kKnightIdFieldNumber = 2;
  inline ::google::protobuf::int32 knightid() const;
  inline void set_knightid(::google::protobuf::int32 value);

  // optional int32 cityId = 3;
  inline bool has_cityid() const;
  inline void clear_cityid();
  static const int kCityIdFieldNumber = 3;
  inline ::google::protobuf::int32 cityid() const;
  inline void set_cityid(::google::protobuf::int32 value);

  // optional int32 marchId = 4;
  inline bool has_marchid() const;
  inline void clear_marchid();
  static const int kMarchIdFieldNumber = 4;
  inline ::google::protobuf::int32 marchid() const;
  inline void set_marchid(::google::protobuf::int32 value);

  // optional int32 levelId = 5;
  inline bool has_levelid() const;
  inline void clear_levelid();
  static const int kLevelIdFieldNumber = 5;
  inline ::google::protobuf::int32 levelid() const;
  inline void set_levelid(::google::protobuf::int32 value);

  // repeated int32 units = 6;
  inline int units_size() const;
  inline void clear_units();
  static const int kUnitsFieldNumber = 6;
  inline ::google::protobuf::int32 units(int index) const;
  inline void set_units(int index, ::google::protobuf::int32 value);
  inline void add_units(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      units() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_units();

  // @@protoc_insertion_point(class_scope:PBMsgReqPve)
 private:
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_knightid();
  inline void clear_has_knightid();
  inline void set_has_cityid();
  inline void clear_has_cityid();
  inline void set_has_marchid();
  inline void clear_has_marchid();
  inline void set_has_levelid();
  inline void clear_has_levelid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 type_;
  ::google::protobuf::int32 knightid_;
  ::google::protobuf::int32 cityid_;
  ::google::protobuf::int32 marchid_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > units_;
  ::google::protobuf::int32 levelid_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(6 + 31) / 32];

  friend void  protobuf_AddDesc_PBMsgReqPve_2eproto();
  friend void protobuf_AssignDesc_PBMsgReqPve_2eproto();
  friend void protobuf_ShutdownFile_PBMsgReqPve_2eproto();

  void InitAsDefaultInstance();
  static PBMsgReqPve* default_instance_;
};
// ===================================================================


// ===================================================================

// PBMsgReqPve

// optional int32 type = 1;
inline bool PBMsgReqPve::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PBMsgReqPve::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PBMsgReqPve::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PBMsgReqPve::clear_type() {
  type_ = 0;
  clear_has_type();
}
inline ::google::protobuf::int32 PBMsgReqPve::type() const {
  return type_;
}
inline void PBMsgReqPve::set_type(::google::protobuf::int32 value) {
  set_has_type();
  type_ = value;
}

// optional int32 knightId = 2;
inline bool PBMsgReqPve::has_knightid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void PBMsgReqPve::set_has_knightid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void PBMsgReqPve::clear_has_knightid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void PBMsgReqPve::clear_knightid() {
  knightid_ = 0;
  clear_has_knightid();
}
inline ::google::protobuf::int32 PBMsgReqPve::knightid() const {
  return knightid_;
}
inline void PBMsgReqPve::set_knightid(::google::protobuf::int32 value) {
  set_has_knightid();
  knightid_ = value;
}

// optional int32 cityId = 3;
inline bool PBMsgReqPve::has_cityid() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void PBMsgReqPve::set_has_cityid() {
  _has_bits_[0] |= 0x00000004u;
}
inline void PBMsgReqPve::clear_has_cityid() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void PBMsgReqPve::clear_cityid() {
  cityid_ = 0;
  clear_has_cityid();
}
inline ::google::protobuf::int32 PBMsgReqPve::cityid() const {
  return cityid_;
}
inline void PBMsgReqPve::set_cityid(::google::protobuf::int32 value) {
  set_has_cityid();
  cityid_ = value;
}

// optional int32 marchId = 4;
inline bool PBMsgReqPve::has_marchid() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void PBMsgReqPve::set_has_marchid() {
  _has_bits_[0] |= 0x00000008u;
}
inline void PBMsgReqPve::clear_has_marchid() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void PBMsgReqPve::clear_marchid() {
  marchid_ = 0;
  clear_has_marchid();
}
inline ::google::protobuf::int32 PBMsgReqPve::marchid() const {
  return marchid_;
}
inline void PBMsgReqPve::set_marchid(::google::protobuf::int32 value) {
  set_has_marchid();
  marchid_ = value;
}

// optional int32 levelId = 5;
inline bool PBMsgReqPve::has_levelid() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void PBMsgReqPve::set_has_levelid() {
  _has_bits_[0] |= 0x00000010u;
}
inline void PBMsgReqPve::clear_has_levelid() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void PBMsgReqPve::clear_levelid() {
  levelid_ = 0;
  clear_has_levelid();
}
inline ::google::protobuf::int32 PBMsgReqPve::levelid() const {
  return levelid_;
}
inline void PBMsgReqPve::set_levelid(::google::protobuf::int32 value) {
  set_has_levelid();
  levelid_ = value;
}

// repeated int32 units = 6;
inline int PBMsgReqPve::units_size() const {
  return units_.size();
}
inline void PBMsgReqPve::clear_units() {
  units_.Clear();
}
inline ::google::protobuf::int32 PBMsgReqPve::units(int index) const {
  return units_.Get(index);
}
inline void PBMsgReqPve::set_units(int index, ::google::protobuf::int32 value) {
  units_.Set(index, value);
}
inline void PBMsgReqPve::add_units(::google::protobuf::int32 value) {
  units_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
PBMsgReqPve::units() const {
  return units_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
PBMsgReqPve::mutable_units() {
  return &units_;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_PBMsgReqPve_2eproto__INCLUDED
