// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PBMsgHeroItemList.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "PBMsgHeroItemList.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* PBMsgHeroItemList_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  PBMsgHeroItemList_reflection_ = NULL;
const ::google::protobuf::Descriptor* PBMsgHeroItemList_PBMsgHeroItem_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  PBMsgHeroItemList_PBMsgHeroItem_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_PBMsgHeroItemList_2eproto() {
  protobuf_AddDesc_PBMsgHeroItemList_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "PBMsgHeroItemList.proto");
  GOOGLE_CHECK(file != NULL);
  PBMsgHeroItemList_descriptor_ = file->message_type(0);
  static const int PBMsgHeroItemList_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PBMsgHeroItemList, heroitem_),
  };
  PBMsgHeroItemList_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      PBMsgHeroItemList_descriptor_,
      PBMsgHeroItemList::default_instance_,
      PBMsgHeroItemList_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PBMsgHeroItemList, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PBMsgHeroItemList, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(PBMsgHeroItemList));
  PBMsgHeroItemList_PBMsgHeroItem_descriptor_ = PBMsgHeroItemList_descriptor_->nested_type(0);
  static const int PBMsgHeroItemList_PBMsgHeroItem_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PBMsgHeroItemList_PBMsgHeroItem, itemid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PBMsgHeroItemList_PBMsgHeroItem, addrenown_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PBMsgHeroItemList_PBMsgHeroItem, own_),
  };
  PBMsgHeroItemList_PBMsgHeroItem_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      PBMsgHeroItemList_PBMsgHeroItem_descriptor_,
      PBMsgHeroItemList_PBMsgHeroItem::default_instance_,
      PBMsgHeroItemList_PBMsgHeroItem_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PBMsgHeroItemList_PBMsgHeroItem, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PBMsgHeroItemList_PBMsgHeroItem, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(PBMsgHeroItemList_PBMsgHeroItem));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_PBMsgHeroItemList_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    PBMsgHeroItemList_descriptor_, &PBMsgHeroItemList::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    PBMsgHeroItemList_PBMsgHeroItem_descriptor_, &PBMsgHeroItemList_PBMsgHeroItem::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_PBMsgHeroItemList_2eproto() {
  delete PBMsgHeroItemList::default_instance_;
  delete PBMsgHeroItemList_reflection_;
  delete PBMsgHeroItemList_PBMsgHeroItem::default_instance_;
  delete PBMsgHeroItemList_PBMsgHeroItem_reflection_;
}

void protobuf_AddDesc_PBMsgHeroItemList_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\027PBMsgHeroItemList.proto\"\210\001\n\021PBMsgHeroI"
    "temList\0222\n\010heroItem\030\001 \003(\0132 .PBMsgHeroIte"
    "mList.PBMsgHeroItem\032\?\n\rPBMsgHeroItem\022\016\n\006"
    "itemId\030\001 \002(\005\022\021\n\taddRenown\030\002 \002(\005\022\013\n\003own\030\003"
    " \002(\005", 164);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "PBMsgHeroItemList.proto", &protobuf_RegisterTypes);
  PBMsgHeroItemList::default_instance_ = new PBMsgHeroItemList();
  PBMsgHeroItemList_PBMsgHeroItem::default_instance_ = new PBMsgHeroItemList_PBMsgHeroItem();
  PBMsgHeroItemList::default_instance_->InitAsDefaultInstance();
  PBMsgHeroItemList_PBMsgHeroItem::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_PBMsgHeroItemList_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_PBMsgHeroItemList_2eproto {
  StaticDescriptorInitializer_PBMsgHeroItemList_2eproto() {
    protobuf_AddDesc_PBMsgHeroItemList_2eproto();
  }
} static_descriptor_initializer_PBMsgHeroItemList_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int PBMsgHeroItemList_PBMsgHeroItem::kItemIdFieldNumber;
const int PBMsgHeroItemList_PBMsgHeroItem::kAddRenownFieldNumber;
const int PBMsgHeroItemList_PBMsgHeroItem::kOwnFieldNumber;
#endif  // !_MSC_VER

PBMsgHeroItemList_PBMsgHeroItem::PBMsgHeroItemList_PBMsgHeroItem()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void PBMsgHeroItemList_PBMsgHeroItem::InitAsDefaultInstance() {
}

PBMsgHeroItemList_PBMsgHeroItem::PBMsgHeroItemList_PBMsgHeroItem(const PBMsgHeroItemList_PBMsgHeroItem& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void PBMsgHeroItemList_PBMsgHeroItem::SharedCtor() {
  _cached_size_ = 0;
  itemid_ = 0;
  addrenown_ = 0;
  own_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

PBMsgHeroItemList_PBMsgHeroItem::~PBMsgHeroItemList_PBMsgHeroItem() {
  SharedDtor();
}

void PBMsgHeroItemList_PBMsgHeroItem::SharedDtor() {
  if (this != default_instance_) {
  }
}

void PBMsgHeroItemList_PBMsgHeroItem::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PBMsgHeroItemList_PBMsgHeroItem::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PBMsgHeroItemList_PBMsgHeroItem_descriptor_;
}

const PBMsgHeroItemList_PBMsgHeroItem& PBMsgHeroItemList_PBMsgHeroItem::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_PBMsgHeroItemList_2eproto();
  return *default_instance_;
}

PBMsgHeroItemList_PBMsgHeroItem* PBMsgHeroItemList_PBMsgHeroItem::default_instance_ = NULL;

PBMsgHeroItemList_PBMsgHeroItem* PBMsgHeroItemList_PBMsgHeroItem::New() const {
  return new PBMsgHeroItemList_PBMsgHeroItem;
}

void PBMsgHeroItemList_PBMsgHeroItem::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    itemid_ = 0;
    addrenown_ = 0;
    own_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool PBMsgHeroItemList_PBMsgHeroItem::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 itemId = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &itemid_)));
          set_has_itemid();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_addRenown;
        break;
      }

      // required int32 addRenown = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_addRenown:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &addrenown_)));
          set_has_addrenown();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_own;
        break;
      }

      // required int32 own = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_own:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &own_)));
          set_has_own();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void PBMsgHeroItemList_PBMsgHeroItem::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required int32 itemId = 1;
  if (has_itemid()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->itemid(), output);
  }

  // required int32 addRenown = 2;
  if (has_addrenown()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->addrenown(), output);
  }

  // required int32 own = 3;
  if (has_own()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->own(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* PBMsgHeroItemList_PBMsgHeroItem::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required int32 itemId = 1;
  if (has_itemid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->itemid(), target);
  }

  // required int32 addRenown = 2;
  if (has_addrenown()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->addrenown(), target);
  }

  // required int32 own = 3;
  if (has_own()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->own(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int PBMsgHeroItemList_PBMsgHeroItem::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 itemId = 1;
    if (has_itemid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->itemid());
    }

    // required int32 addRenown = 2;
    if (has_addrenown()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->addrenown());
    }

    // required int32 own = 3;
    if (has_own()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->own());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PBMsgHeroItemList_PBMsgHeroItem::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const PBMsgHeroItemList_PBMsgHeroItem* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const PBMsgHeroItemList_PBMsgHeroItem*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void PBMsgHeroItemList_PBMsgHeroItem::MergeFrom(const PBMsgHeroItemList_PBMsgHeroItem& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_itemid()) {
      set_itemid(from.itemid());
    }
    if (from.has_addrenown()) {
      set_addrenown(from.addrenown());
    }
    if (from.has_own()) {
      set_own(from.own());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void PBMsgHeroItemList_PBMsgHeroItem::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PBMsgHeroItemList_PBMsgHeroItem::CopyFrom(const PBMsgHeroItemList_PBMsgHeroItem& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PBMsgHeroItemList_PBMsgHeroItem::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;

  return true;
}

void PBMsgHeroItemList_PBMsgHeroItem::Swap(PBMsgHeroItemList_PBMsgHeroItem* other) {
  if (other != this) {
    std::swap(itemid_, other->itemid_);
    std::swap(addrenown_, other->addrenown_);
    std::swap(own_, other->own_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata PBMsgHeroItemList_PBMsgHeroItem::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = PBMsgHeroItemList_PBMsgHeroItem_descriptor_;
  metadata.reflection = PBMsgHeroItemList_PBMsgHeroItem_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int PBMsgHeroItemList::kHeroItemFieldNumber;
#endif  // !_MSC_VER

PBMsgHeroItemList::PBMsgHeroItemList()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void PBMsgHeroItemList::InitAsDefaultInstance() {
}

PBMsgHeroItemList::PBMsgHeroItemList(const PBMsgHeroItemList& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void PBMsgHeroItemList::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

PBMsgHeroItemList::~PBMsgHeroItemList() {
  SharedDtor();
}

void PBMsgHeroItemList::SharedDtor() {
  if (this != default_instance_) {
  }
}

void PBMsgHeroItemList::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PBMsgHeroItemList::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PBMsgHeroItemList_descriptor_;
}

const PBMsgHeroItemList& PBMsgHeroItemList::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_PBMsgHeroItemList_2eproto();
  return *default_instance_;
}

PBMsgHeroItemList* PBMsgHeroItemList::default_instance_ = NULL;

PBMsgHeroItemList* PBMsgHeroItemList::New() const {
  return new PBMsgHeroItemList;
}

void PBMsgHeroItemList::Clear() {
  heroitem_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool PBMsgHeroItemList::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .PBMsgHeroItemList.PBMsgHeroItem heroItem = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_heroItem:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_heroitem()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(10)) goto parse_heroItem;
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void PBMsgHeroItemList::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated .PBMsgHeroItemList.PBMsgHeroItem heroItem = 1;
  for (int i = 0; i < this->heroitem_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->heroitem(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* PBMsgHeroItemList::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // repeated .PBMsgHeroItemList.PBMsgHeroItem heroItem = 1;
  for (int i = 0; i < this->heroitem_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->heroitem(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int PBMsgHeroItemList::ByteSize() const {
  int total_size = 0;

  // repeated .PBMsgHeroItemList.PBMsgHeroItem heroItem = 1;
  total_size += 1 * this->heroitem_size();
  for (int i = 0; i < this->heroitem_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->heroitem(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PBMsgHeroItemList::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const PBMsgHeroItemList* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const PBMsgHeroItemList*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void PBMsgHeroItemList::MergeFrom(const PBMsgHeroItemList& from) {
  GOOGLE_CHECK_NE(&from, this);
  heroitem_.MergeFrom(from.heroitem_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void PBMsgHeroItemList::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PBMsgHeroItemList::CopyFrom(const PBMsgHeroItemList& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PBMsgHeroItemList::IsInitialized() const {

  for (int i = 0; i < heroitem_size(); i++) {
    if (!this->heroitem(i).IsInitialized()) return false;
  }
  return true;
}

void PBMsgHeroItemList::Swap(PBMsgHeroItemList* other) {
  if (other != this) {
    heroitem_.Swap(&other->heroitem_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata PBMsgHeroItemList::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = PBMsgHeroItemList_descriptor_;
  metadata.reflection = PBMsgHeroItemList_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
