// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PBMsgProcessHeroExplore.proto

#ifndef PROTOBUF_PBMsgProcessHeroExplore_2eproto__INCLUDED
#define PROTOBUF_PBMsgProcessHeroExplore_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_PBMsgProcessHeroExplore_2eproto();
void protobuf_AssignDesc_PBMsgProcessHeroExplore_2eproto();
void protobuf_ShutdownFile_PBMsgProcessHeroExplore_2eproto();

class PBMsgProcessHeroExplore;

// ===================================================================

class PBMsgProcessHeroExplore : public ::google::protobuf::Message {
 public:
  PBMsgProcessHeroExplore();
  virtual ~PBMsgProcessHeroExplore();

  PBMsgProcessHeroExplore(const PBMsgProcessHeroExplore& from);

  inline PBMsgProcessHeroExplore& operator=(const PBMsgProcessHeroExplore& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PBMsgProcessHeroExplore& default_instance();

  void Swap(PBMsgProcessHeroExplore* other);

  // implements Message ----------------------------------------------

  PBMsgProcessHeroExplore* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PBMsgProcessHeroExplore& from);
  void MergeFrom(const PBMsgProcessHeroExplore& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int64 exploreId = 1;
  inline bool has_exploreid() const;
  inline void clear_exploreid();
  static const int kExploreIdFieldNumber = 1;
  inline ::google::protobuf::int64 exploreid() const;
  inline void set_exploreid(::google::protobuf::int64 value);

  // required int32 strength = 2;
  inline bool has_strength() const;
  inline void clear_strength();
  static const int kStrengthFieldNumber = 2;
  inline ::google::protobuf::int32 strength() const;
  inline void set_strength(::google::protobuf::int32 value);

  // optional int32 itemId = 3;
  inline bool has_itemid() const;
  inline void clear_itemid();
  static const int kItemIdFieldNumber = 3;
  inline ::google::protobuf::int32 itemid() const;
  inline void set_itemid(::google::protobuf::int32 value);

  // optional int32 itemCount = 4;
  inline bool has_itemcount() const;
  inline void clear_itemcount();
  static const int kItemCountFieldNumber = 4;
  inline ::google::protobuf::int32 itemcount() const;
  inline void set_itemcount(::google::protobuf::int32 value);

  // optional int32 gems = 5;
  inline bool has_gems() const;
  inline void clear_gems();
  static const int kGemsFieldNumber = 5;
  inline ::google::protobuf::int32 gems() const;
  inline void set_gems(::google::protobuf::int32 value);

  // required int32 gemsN = 6;
  inline bool has_gemsn() const;
  inline void clear_gemsn();
  static const int kGemsNFieldNumber = 6;
  inline ::google::protobuf::int32 gemsn() const;
  inline void set_gemsn(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:PBMsgProcessHeroExplore)
 private:
  inline void set_has_exploreid();
  inline void clear_has_exploreid();
  inline void set_has_strength();
  inline void clear_has_strength();
  inline void set_has_itemid();
  inline void clear_has_itemid();
  inline void set_has_itemcount();
  inline void clear_has_itemcount();
  inline void set_has_gems();
  inline void clear_has_gems();
  inline void set_has_gemsn();
  inline void clear_has_gemsn();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int64 exploreid_;
  ::google::protobuf::int32 strength_;
  ::google::protobuf::int32 itemid_;
  ::google::protobuf::int32 itemcount_;
  ::google::protobuf::int32 gems_;
  ::google::protobuf::int32 gemsn_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(6 + 31) / 32];

  friend void  protobuf_AddDesc_PBMsgProcessHeroExplore_2eproto();
  friend void protobuf_AssignDesc_PBMsgProcessHeroExplore_2eproto();
  friend void protobuf_ShutdownFile_PBMsgProcessHeroExplore_2eproto();

  void InitAsDefaultInstance();
  static PBMsgProcessHeroExplore* default_instance_;
};
// ===================================================================


// ===================================================================

// PBMsgProcessHeroExplore

// required int64 exploreId = 1;
inline bool PBMsgProcessHeroExplore::has_exploreid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PBMsgProcessHeroExplore::set_has_exploreid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PBMsgProcessHeroExplore::clear_has_exploreid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PBMsgProcessHeroExplore::clear_exploreid() {
  exploreid_ = GOOGLE_LONGLONG(0);
  clear_has_exploreid();
}
inline ::google::protobuf::int64 PBMsgProcessHeroExplore::exploreid() const {
  return exploreid_;
}
inline void PBMsgProcessHeroExplore::set_exploreid(::google::protobuf::int64 value) {
  set_has_exploreid();
  exploreid_ = value;
}

// required int32 strength = 2;
inline bool PBMsgProcessHeroExplore::has_strength() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void PBMsgProcessHeroExplore::set_has_strength() {
  _has_bits_[0] |= 0x00000002u;
}
inline void PBMsgProcessHeroExplore::clear_has_strength() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void PBMsgProcessHeroExplore::clear_strength() {
  strength_ = 0;
  clear_has_strength();
}
inline ::google::protobuf::int32 PBMsgProcessHeroExplore::strength() const {
  return strength_;
}
inline void PBMsgProcessHeroExplore::set_strength(::google::protobuf::int32 value) {
  set_has_strength();
  strength_ = value;
}

// optional int32 itemId = 3;
inline bool PBMsgProcessHeroExplore::has_itemid() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void PBMsgProcessHeroExplore::set_has_itemid() {
  _has_bits_[0] |= 0x00000004u;
}
inline void PBMsgProcessHeroExplore::clear_has_itemid() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void PBMsgProcessHeroExplore::clear_itemid() {
  itemid_ = 0;
  clear_has_itemid();
}
inline ::google::protobuf::int32 PBMsgProcessHeroExplore::itemid() const {
  return itemid_;
}
inline void PBMsgProcessHeroExplore::set_itemid(::google::protobuf::int32 value) {
  set_has_itemid();
  itemid_ = value;
}

// optional int32 itemCount = 4;
inline bool PBMsgProcessHeroExplore::has_itemcount() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void PBMsgProcessHeroExplore::set_has_itemcount() {
  _has_bits_[0] |= 0x00000008u;
}
inline void PBMsgProcessHeroExplore::clear_has_itemcount() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void PBMsgProcessHeroExplore::clear_itemcount() {
  itemcount_ = 0;
  clear_has_itemcount();
}
inline ::google::protobuf::int32 PBMsgProcessHeroExplore::itemcount() const {
  return itemcount_;
}
inline void PBMsgProcessHeroExplore::set_itemcount(::google::protobuf::int32 value) {
  set_has_itemcount();
  itemcount_ = value;
}

// optional int32 gems = 5;
inline bool PBMsgProcessHeroExplore::has_gems() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void PBMsgProcessHeroExplore::set_has_gems() {
  _has_bits_[0] |= 0x00000010u;
}
inline void PBMsgProcessHeroExplore::clear_has_gems() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void PBMsgProcessHeroExplore::clear_gems() {
  gems_ = 0;
  clear_has_gems();
}
inline ::google::protobuf::int32 PBMsgProcessHeroExplore::gems() const {
  return gems_;
}
inline void PBMsgProcessHeroExplore::set_gems(::google::protobuf::int32 value) {
  set_has_gems();
  gems_ = value;
}

// required int32 gemsN = 6;
inline bool PBMsgProcessHeroExplore::has_gemsn() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void PBMsgProcessHeroExplore::set_has_gemsn() {
  _has_bits_[0] |= 0x00000020u;
}
inline void PBMsgProcessHeroExplore::clear_has_gemsn() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void PBMsgProcessHeroExplore::clear_gemsn() {
  gemsn_ = 0;
  clear_has_gemsn();
}
inline ::google::protobuf::int32 PBMsgProcessHeroExplore::gemsn() const {
  return gemsn_;
}
inline void PBMsgProcessHeroExplore::set_gemsn(::google::protobuf::int32 value) {
  set_has_gemsn();
  gemsn_ = value;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_PBMsgProcessHeroExplore_2eproto__INCLUDED
