// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PBMsgHeroInfo.proto

#ifndef PROTOBUF_PBMsgHeroInfo_2eproto__INCLUDED
#define PROTOBUF_PBMsgHeroInfo_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_PBMsgHeroInfo_2eproto();
void protobuf_AssignDesc_PBMsgHeroInfo_2eproto();
void protobuf_ShutdownFile_PBMsgHeroInfo_2eproto();

class PBMsgHeroInfo;

// ===================================================================

class PBMsgHeroInfo : public ::google::protobuf::Message {
 public:
  PBMsgHeroInfo();
  virtual ~PBMsgHeroInfo();

  PBMsgHeroInfo(const PBMsgHeroInfo& from);

  inline PBMsgHeroInfo& operator=(const PBMsgHeroInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PBMsgHeroInfo& default_instance();

  void Swap(PBMsgHeroInfo* other);

  // implements Message ----------------------------------------------

  PBMsgHeroInfo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PBMsgHeroInfo& from);
  void MergeFrom(const PBMsgHeroInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 score = 1;
  inline bool has_score() const;
  inline void clear_score();
  static const int kScoreFieldNumber = 1;
  inline ::google::protobuf::int32 score() const;
  inline void set_score(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:PBMsgHeroInfo)
 private:
  inline void set_has_score();
  inline void clear_has_score();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 score_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_PBMsgHeroInfo_2eproto();
  friend void protobuf_AssignDesc_PBMsgHeroInfo_2eproto();
  friend void protobuf_ShutdownFile_PBMsgHeroInfo_2eproto();

  void InitAsDefaultInstance();
  static PBMsgHeroInfo* default_instance_;
};
// ===================================================================


// ===================================================================

// PBMsgHeroInfo

// optional int32 score = 1;
inline bool PBMsgHeroInfo::has_score() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PBMsgHeroInfo::set_has_score() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PBMsgHeroInfo::clear_has_score() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PBMsgHeroInfo::clear_score() {
  score_ = 0;
  clear_has_score();
}
inline ::google::protobuf::int32 PBMsgHeroInfo::score() const {
  return score_;
}
inline void PBMsgHeroInfo::set_score(::google::protobuf::int32 value) {
  set_has_score();
  score_ = value;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_PBMsgHeroInfo_2eproto__INCLUDED
