// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PBMsgReqPve.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "PBMsgReqPve.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* PBMsgReqPve_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  PBMsgReqPve_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_PBMsgReqPve_2eproto() {
  protobuf_AddDesc_PBMsgReqPve_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "PBMsgReqPve.proto");
  GOOGLE_CHECK(file != NULL);
  PBMsgReqPve_descriptor_ = file->message_type(0);
  static const int PBMsgReqPve_offsets_[6] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PBMsgReqPve, type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PBMsgReqPve, knightid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PBMsgReqPve, cityid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PBMsgReqPve, marchid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PBMsgReqPve, levelid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PBMsgReqPve, units_),
  };
  PBMsgReqPve_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      PBMsgReqPve_descriptor_,
      PBMsgReqPve::default_instance_,
      PBMsgReqPve_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PBMsgReqPve, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PBMsgReqPve, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(PBMsgReqPve));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_PBMsgReqPve_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    PBMsgReqPve_descriptor_, &PBMsgReqPve::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_PBMsgReqPve_2eproto() {
  delete PBMsgReqPve::default_instance_;
  delete PBMsgReqPve_reflection_;
}

void protobuf_AddDesc_PBMsgReqPve_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\021PBMsgReqPve.proto\"n\n\013PBMsgReqPve\022\014\n\004ty"
    "pe\030\001 \001(\005\022\020\n\010knightId\030\002 \001(\005\022\016\n\006cityId\030\003 \001"
    "(\005\022\017\n\007marchId\030\004 \001(\005\022\017\n\007levelId\030\005 \001(\005\022\r\n\005"
    "units\030\006 \003(\005", 131);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "PBMsgReqPve.proto", &protobuf_RegisterTypes);
  PBMsgReqPve::default_instance_ = new PBMsgReqPve();
  PBMsgReqPve::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_PBMsgReqPve_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_PBMsgReqPve_2eproto {
  StaticDescriptorInitializer_PBMsgReqPve_2eproto() {
    protobuf_AddDesc_PBMsgReqPve_2eproto();
  }
} static_descriptor_initializer_PBMsgReqPve_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int PBMsgReqPve::kTypeFieldNumber;
const int PBMsgReqPve::kKnightIdFieldNumber;
const int PBMsgReqPve::kCityIdFieldNumber;
const int PBMsgReqPve::kMarchIdFieldNumber;
const int PBMsgReqPve::kLevelIdFieldNumber;
const int PBMsgReqPve::kUnitsFieldNumber;
#endif  // !_MSC_VER

PBMsgReqPve::PBMsgReqPve()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void PBMsgReqPve::InitAsDefaultInstance() {
}

PBMsgReqPve::PBMsgReqPve(const PBMsgReqPve& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void PBMsgReqPve::SharedCtor() {
  _cached_size_ = 0;
  type_ = 0;
  knightid_ = 0;
  cityid_ = 0;
  marchid_ = 0;
  levelid_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

PBMsgReqPve::~PBMsgReqPve() {
  SharedDtor();
}

void PBMsgReqPve::SharedDtor() {
  if (this != default_instance_) {
  }
}

void PBMsgReqPve::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PBMsgReqPve::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PBMsgReqPve_descriptor_;
}

const PBMsgReqPve& PBMsgReqPve::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_PBMsgReqPve_2eproto();
  return *default_instance_;
}

PBMsgReqPve* PBMsgReqPve::default_instance_ = NULL;

PBMsgReqPve* PBMsgReqPve::New() const {
  return new PBMsgReqPve;
}

void PBMsgReqPve::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    type_ = 0;
    knightid_ = 0;
    cityid_ = 0;
    marchid_ = 0;
    levelid_ = 0;
  }
  units_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool PBMsgReqPve::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 type = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &type_)));
          set_has_type();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_knightId;
        break;
      }

      // optional int32 knightId = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_knightId:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &knightid_)));
          set_has_knightid();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_cityId;
        break;
      }

      // optional int32 cityId = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_cityId:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &cityid_)));
          set_has_cityid();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(32)) goto parse_marchId;
        break;
      }

      // optional int32 marchId = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_marchId:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &marchid_)));
          set_has_marchid();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(40)) goto parse_levelId;
        break;
      }

      // optional int32 levelId = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_levelId:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &levelid_)));
          set_has_levelid();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(48)) goto parse_units;
        break;
      }

      // repeated int32 units = 6;
      case 6: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_units:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 48, input, this->mutable_units())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_units())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(48)) goto parse_units;
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void PBMsgReqPve::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional int32 type = 1;
  if (has_type()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->type(), output);
  }

  // optional int32 knightId = 2;
  if (has_knightid()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->knightid(), output);
  }

  // optional int32 cityId = 3;
  if (has_cityid()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->cityid(), output);
  }

  // optional int32 marchId = 4;
  if (has_marchid()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->marchid(), output);
  }

  // optional int32 levelId = 5;
  if (has_levelid()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->levelid(), output);
  }

  // repeated int32 units = 6;
  for (int i = 0; i < this->units_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(
      6, this->units(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* PBMsgReqPve::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional int32 type = 1;
  if (has_type()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->type(), target);
  }

  // optional int32 knightId = 2;
  if (has_knightid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->knightid(), target);
  }

  // optional int32 cityId = 3;
  if (has_cityid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->cityid(), target);
  }

  // optional int32 marchId = 4;
  if (has_marchid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->marchid(), target);
  }

  // optional int32 levelId = 5;
  if (has_levelid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->levelid(), target);
  }

  // repeated int32 units = 6;
  for (int i = 0; i < this->units_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32ToArray(6, this->units(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int PBMsgReqPve::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional int32 type = 1;
    if (has_type()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->type());
    }

    // optional int32 knightId = 2;
    if (has_knightid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->knightid());
    }

    // optional int32 cityId = 3;
    if (has_cityid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->cityid());
    }

    // optional int32 marchId = 4;
    if (has_marchid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->marchid());
    }

    // optional int32 levelId = 5;
    if (has_levelid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->levelid());
    }

  }
  // repeated int32 units = 6;
  {
    int data_size = 0;
    for (int i = 0; i < this->units_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        Int32Size(this->units(i));
    }
    total_size += 1 * this->units_size() + data_size;
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PBMsgReqPve::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const PBMsgReqPve* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const PBMsgReqPve*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void PBMsgReqPve::MergeFrom(const PBMsgReqPve& from) {
  GOOGLE_CHECK_NE(&from, this);
  units_.MergeFrom(from.units_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_type()) {
      set_type(from.type());
    }
    if (from.has_knightid()) {
      set_knightid(from.knightid());
    }
    if (from.has_cityid()) {
      set_cityid(from.cityid());
    }
    if (from.has_marchid()) {
      set_marchid(from.marchid());
    }
    if (from.has_levelid()) {
      set_levelid(from.levelid());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void PBMsgReqPve::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PBMsgReqPve::CopyFrom(const PBMsgReqPve& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PBMsgReqPve::IsInitialized() const {

  return true;
}

void PBMsgReqPve::Swap(PBMsgReqPve* other) {
  if (other != this) {
    std::swap(type_, other->type_);
    std::swap(knightid_, other->knightid_);
    std::swap(cityid_, other->cityid_);
    std::swap(marchid_, other->marchid_);
    std::swap(levelid_, other->levelid_);
    units_.Swap(&other->units_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata PBMsgReqPve::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = PBMsgReqPve_descriptor_;
  metadata.reflection = PBMsgReqPve_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
