// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PBMsgResponse.proto

#ifndef PROTOBUF_PBMsgResponse_2eproto__INCLUDED
#define PROTOBUF_PBMsgResponse_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_PBMsgResponse_2eproto();
void protobuf_AssignDesc_PBMsgResponse_2eproto();
void protobuf_ShutdownFile_PBMsgResponse_2eproto();

class PBMsgResponse;

// ===================================================================

class PBMsgResponse : public ::google::protobuf::Message {
 public:
  PBMsgResponse();
  virtual ~PBMsgResponse();

  PBMsgResponse(const PBMsgResponse& from);

  inline PBMsgResponse& operator=(const PBMsgResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PBMsgResponse& default_instance();

  void Swap(PBMsgResponse* other);

  // implements Message ----------------------------------------------

  PBMsgResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PBMsgResponse& from);
  void MergeFrom(const PBMsgResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required bool ok = 1;
  inline bool has_ok() const;
  inline void clear_ok();
  static const int kOkFieldNumber = 1;
  inline bool ok() const;
  inline void set_ok(bool value);

  // optional int32 error_code = 2;
  inline bool has_error_code() const;
  inline void clear_error_code();
  static const int kErrorCodeFieldNumber = 2;
  inline ::google::protobuf::int32 error_code() const;
  inline void set_error_code(::google::protobuf::int32 value);

  // optional string msg = 3;
  inline bool has_msg() const;
  inline void clear_msg();
  static const int kMsgFieldNumber = 3;
  inline const ::std::string& msg() const;
  inline void set_msg(const ::std::string& value);
  inline void set_msg(const char* value);
  inline void set_msg(const char* value, size_t size);
  inline ::std::string* mutable_msg();
  inline ::std::string* release_msg();
  inline void set_allocated_msg(::std::string* msg);

  // optional bytes data = 4;
  inline bool has_data() const;
  inline void clear_data();
  static const int kDataFieldNumber = 4;
  inline const ::std::string& data() const;
  inline void set_data(const ::std::string& value);
  inline void set_data(const char* value);
  inline void set_data(const void* value, size_t size);
  inline ::std::string* mutable_data();
  inline ::std::string* release_data();
  inline void set_allocated_data(::std::string* data);

  // @@protoc_insertion_point(class_scope:PBMsgResponse)
 private:
  inline void set_has_ok();
  inline void clear_has_ok();
  inline void set_has_error_code();
  inline void clear_has_error_code();
  inline void set_has_msg();
  inline void clear_has_msg();
  inline void set_has_data();
  inline void clear_has_data();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  bool ok_;
  ::google::protobuf::int32 error_code_;
  ::std::string* msg_;
  ::std::string* data_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];

  friend void  protobuf_AddDesc_PBMsgResponse_2eproto();
  friend void protobuf_AssignDesc_PBMsgResponse_2eproto();
  friend void protobuf_ShutdownFile_PBMsgResponse_2eproto();

  void InitAsDefaultInstance();
  static PBMsgResponse* default_instance_;
};
// ===================================================================


// ===================================================================

// PBMsgResponse

// required bool ok = 1;
inline bool PBMsgResponse::has_ok() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PBMsgResponse::set_has_ok() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PBMsgResponse::clear_has_ok() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PBMsgResponse::clear_ok() {
  ok_ = false;
  clear_has_ok();
}
inline bool PBMsgResponse::ok() const {
  return ok_;
}
inline void PBMsgResponse::set_ok(bool value) {
  set_has_ok();
  ok_ = value;
}

// optional int32 error_code = 2;
inline bool PBMsgResponse::has_error_code() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void PBMsgResponse::set_has_error_code() {
  _has_bits_[0] |= 0x00000002u;
}
inline void PBMsgResponse::clear_has_error_code() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void PBMsgResponse::clear_error_code() {
  error_code_ = 0;
  clear_has_error_code();
}
inline ::google::protobuf::int32 PBMsgResponse::error_code() const {
  return error_code_;
}
inline void PBMsgResponse::set_error_code(::google::protobuf::int32 value) {
  set_has_error_code();
  error_code_ = value;
}

// optional string msg = 3;
inline bool PBMsgResponse::has_msg() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void PBMsgResponse::set_has_msg() {
  _has_bits_[0] |= 0x00000004u;
}
inline void PBMsgResponse::clear_has_msg() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void PBMsgResponse::clear_msg() {
  if (msg_ != &::google::protobuf::internal::kEmptyString) {
    msg_->clear();
  }
  clear_has_msg();
}
inline const ::std::string& PBMsgResponse::msg() const {
  return *msg_;
}
inline void PBMsgResponse::set_msg(const ::std::string& value) {
  set_has_msg();
  if (msg_ == &::google::protobuf::internal::kEmptyString) {
    msg_ = new ::std::string;
  }
  msg_->assign(value);
}
inline void PBMsgResponse::set_msg(const char* value) {
  set_has_msg();
  if (msg_ == &::google::protobuf::internal::kEmptyString) {
    msg_ = new ::std::string;
  }
  msg_->assign(value);
}
inline void PBMsgResponse::set_msg(const char* value, size_t size) {
  set_has_msg();
  if (msg_ == &::google::protobuf::internal::kEmptyString) {
    msg_ = new ::std::string;
  }
  msg_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* PBMsgResponse::mutable_msg() {
  set_has_msg();
  if (msg_ == &::google::protobuf::internal::kEmptyString) {
    msg_ = new ::std::string;
  }
  return msg_;
}
inline ::std::string* PBMsgResponse::release_msg() {
  clear_has_msg();
  if (msg_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = msg_;
    msg_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void PBMsgResponse::set_allocated_msg(::std::string* msg) {
  if (msg_ != &::google::protobuf::internal::kEmptyString) {
    delete msg_;
  }
  if (msg) {
    set_has_msg();
    msg_ = msg;
  } else {
    clear_has_msg();
    msg_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional bytes data = 4;
inline bool PBMsgResponse::has_data() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void PBMsgResponse::set_has_data() {
  _has_bits_[0] |= 0x00000008u;
}
inline void PBMsgResponse::clear_has_data() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void PBMsgResponse::clear_data() {
  if (data_ != &::google::protobuf::internal::kEmptyString) {
    data_->clear();
  }
  clear_has_data();
}
inline const ::std::string& PBMsgResponse::data() const {
  return *data_;
}
inline void PBMsgResponse::set_data(const ::std::string& value) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::kEmptyString) {
    data_ = new ::std::string;
  }
  data_->assign(value);
}
inline void PBMsgResponse::set_data(const char* value) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::kEmptyString) {
    data_ = new ::std::string;
  }
  data_->assign(value);
}
inline void PBMsgResponse::set_data(const void* value, size_t size) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::kEmptyString) {
    data_ = new ::std::string;
  }
  data_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* PBMsgResponse::mutable_data() {
  set_has_data();
  if (data_ == &::google::protobuf::internal::kEmptyString) {
    data_ = new ::std::string;
  }
  return data_;
}
inline ::std::string* PBMsgResponse::release_data() {
  clear_has_data();
  if (data_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = data_;
    data_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void PBMsgResponse::set_allocated_data(::std::string* data) {
  if (data_ != &::google::protobuf::internal::kEmptyString) {
    delete data_;
  }
  if (data) {
    set_has_data();
    data_ = data;
  } else {
    clear_has_data();
    data_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_PBMsgResponse_2eproto__INCLUDED
