// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PBMsgReqHeroHouseList.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "PBMsgReqHeroHouseList.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* PBMsgReqHeroHouseList_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  PBMsgReqHeroHouseList_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_PBMsgReqHeroHouseList_2eproto() {
  protobuf_AddDesc_PBMsgReqHeroHouseList_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "PBMsgReqHeroHouseList.proto");
  GOOGLE_CHECK(file != NULL);
  PBMsgReqHeroHouseList_descriptor_ = file->message_type(0);
  static const int PBMsgReqHeroHouseList_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PBMsgReqHeroHouseList, cid_),
  };
  PBMsgReqHeroHouseList_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      PBMsgReqHeroHouseList_descriptor_,
      PBMsgReqHeroHouseList::default_instance_,
      PBMsgReqHeroHouseList_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PBMsgReqHeroHouseList, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PBMsgReqHeroHouseList, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(PBMsgReqHeroHouseList));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_PBMsgReqHeroHouseList_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    PBMsgReqHeroHouseList_descriptor_, &PBMsgReqHeroHouseList::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_PBMsgReqHeroHouseList_2eproto() {
  delete PBMsgReqHeroHouseList::default_instance_;
  delete PBMsgReqHeroHouseList_reflection_;
}

void protobuf_AddDesc_PBMsgReqHeroHouseList_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\033PBMsgReqHeroHouseList.proto\"$\n\025PBMsgRe"
    "qHeroHouseList\022\013\n\003cid\030\001 \002(\003", 67);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "PBMsgReqHeroHouseList.proto", &protobuf_RegisterTypes);
  PBMsgReqHeroHouseList::default_instance_ = new PBMsgReqHeroHouseList();
  PBMsgReqHeroHouseList::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_PBMsgReqHeroHouseList_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_PBMsgReqHeroHouseList_2eproto {
  StaticDescriptorInitializer_PBMsgReqHeroHouseList_2eproto() {
    protobuf_AddDesc_PBMsgReqHeroHouseList_2eproto();
  }
} static_descriptor_initializer_PBMsgReqHeroHouseList_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int PBMsgReqHeroHouseList::kCidFieldNumber;
#endif  // !_MSC_VER

PBMsgReqHeroHouseList::PBMsgReqHeroHouseList()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void PBMsgReqHeroHouseList::InitAsDefaultInstance() {
}

PBMsgReqHeroHouseList::PBMsgReqHeroHouseList(const PBMsgReqHeroHouseList& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void PBMsgReqHeroHouseList::SharedCtor() {
  _cached_size_ = 0;
  cid_ = GOOGLE_LONGLONG(0);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

PBMsgReqHeroHouseList::~PBMsgReqHeroHouseList() {
  SharedDtor();
}

void PBMsgReqHeroHouseList::SharedDtor() {
  if (this != default_instance_) {
  }
}

void PBMsgReqHeroHouseList::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PBMsgReqHeroHouseList::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PBMsgReqHeroHouseList_descriptor_;
}

const PBMsgReqHeroHouseList& PBMsgReqHeroHouseList::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_PBMsgReqHeroHouseList_2eproto();
  return *default_instance_;
}

PBMsgReqHeroHouseList* PBMsgReqHeroHouseList::default_instance_ = NULL;

PBMsgReqHeroHouseList* PBMsgReqHeroHouseList::New() const {
  return new PBMsgReqHeroHouseList;
}

void PBMsgReqHeroHouseList::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    cid_ = GOOGLE_LONGLONG(0);
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool PBMsgReqHeroHouseList::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int64 cid = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &cid_)));
          set_has_cid();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void PBMsgReqHeroHouseList::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required int64 cid = 1;
  if (has_cid()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->cid(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* PBMsgReqHeroHouseList::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required int64 cid = 1;
  if (has_cid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(1, this->cid(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int PBMsgReqHeroHouseList::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int64 cid = 1;
    if (has_cid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->cid());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PBMsgReqHeroHouseList::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const PBMsgReqHeroHouseList* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const PBMsgReqHeroHouseList*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void PBMsgReqHeroHouseList::MergeFrom(const PBMsgReqHeroHouseList& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_cid()) {
      set_cid(from.cid());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void PBMsgReqHeroHouseList::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PBMsgReqHeroHouseList::CopyFrom(const PBMsgReqHeroHouseList& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PBMsgReqHeroHouseList::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void PBMsgReqHeroHouseList::Swap(PBMsgReqHeroHouseList* other) {
  if (other != this) {
    std::swap(cid_, other->cid_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata PBMsgReqHeroHouseList::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = PBMsgReqHeroHouseList_descriptor_;
  metadata.reflection = PBMsgReqHeroHouseList_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
