// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PBMsgHeroHouseList.proto

#ifndef PROTOBUF_PBMsgHeroHouseList_2eproto__INCLUDED
#define PROTOBUF_PBMsgHeroHouseList_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_PBMsgHeroHouseList_2eproto();
void protobuf_AssignDesc_PBMsgHeroHouseList_2eproto();
void protobuf_ShutdownFile_PBMsgHeroHouseList_2eproto();

class PBMsgHeroHouseList;
class PBMsgHeroHouseList_PBMsgSkillActived;
class PBMsgHeroHouseList_PBMsgHero;

enum PBMsgHeroHouseList_PBMsgHeroStatus {
  PBMsgHeroHouseList_PBMsgHeroStatus_UNLOCKED = 1,
  PBMsgHeroHouseList_PBMsgHeroStatus_IN_CITY_DO_NOTHING = 2,
  PBMsgHeroHouseList_PBMsgHeroStatus_IN_CITY_IN_MARCH = 3,
  PBMsgHeroHouseList_PBMsgHeroStatus_IN_CITY_SLEEP = 4,
  PBMsgHeroHouseList_PBMsgHeroStatus_IN_NO_CITY = 5
};
bool PBMsgHeroHouseList_PBMsgHeroStatus_IsValid(int value);
const PBMsgHeroHouseList_PBMsgHeroStatus PBMsgHeroHouseList_PBMsgHeroStatus_PBMsgHeroStatus_MIN = PBMsgHeroHouseList_PBMsgHeroStatus_UNLOCKED;
const PBMsgHeroHouseList_PBMsgHeroStatus PBMsgHeroHouseList_PBMsgHeroStatus_PBMsgHeroStatus_MAX = PBMsgHeroHouseList_PBMsgHeroStatus_IN_NO_CITY;
const int PBMsgHeroHouseList_PBMsgHeroStatus_PBMsgHeroStatus_ARRAYSIZE = PBMsgHeroHouseList_PBMsgHeroStatus_PBMsgHeroStatus_MAX + 1;

const ::google::protobuf::EnumDescriptor* PBMsgHeroHouseList_PBMsgHeroStatus_descriptor();
inline const ::std::string& PBMsgHeroHouseList_PBMsgHeroStatus_Name(PBMsgHeroHouseList_PBMsgHeroStatus value) {
  return ::google::protobuf::internal::NameOfEnum(
    PBMsgHeroHouseList_PBMsgHeroStatus_descriptor(), value);
}
inline bool PBMsgHeroHouseList_PBMsgHeroStatus_Parse(
    const ::std::string& name, PBMsgHeroHouseList_PBMsgHeroStatus* value) {
  return ::google::protobuf::internal::ParseNamedEnum<PBMsgHeroHouseList_PBMsgHeroStatus>(
    PBMsgHeroHouseList_PBMsgHeroStatus_descriptor(), name, value);
}
// ===================================================================

class PBMsgHeroHouseList_PBMsgSkillActived : public ::google::protobuf::Message {
 public:
  PBMsgHeroHouseList_PBMsgSkillActived();
  virtual ~PBMsgHeroHouseList_PBMsgSkillActived();

  PBMsgHeroHouseList_PBMsgSkillActived(const PBMsgHeroHouseList_PBMsgSkillActived& from);

  inline PBMsgHeroHouseList_PBMsgSkillActived& operator=(const PBMsgHeroHouseList_PBMsgSkillActived& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PBMsgHeroHouseList_PBMsgSkillActived& default_instance();

  void Swap(PBMsgHeroHouseList_PBMsgSkillActived* other);

  // implements Message ----------------------------------------------

  PBMsgHeroHouseList_PBMsgSkillActived* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PBMsgHeroHouseList_PBMsgSkillActived& from);
  void MergeFrom(const PBMsgHeroHouseList_PBMsgSkillActived& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);

  // required bool actived = 2;
  inline bool has_actived() const;
  inline void clear_actived();
  static const int kActivedFieldNumber = 2;
  inline bool actived() const;
  inline void set_actived(bool value);

  // optional int32 lv = 3;
  inline bool has_lv() const;
  inline void clear_lv();
  static const int kLvFieldNumber = 3;
  inline ::google::protobuf::int32 lv() const;
  inline void set_lv(::google::protobuf::int32 value);

  // optional int32 hero = 4;
  inline bool has_hero() const;
  inline void clear_hero();
  static const int kHeroFieldNumber = 4;
  inline ::google::protobuf::int32 hero() const;
  inline void set_hero(::google::protobuf::int32 value);

  // optional int32 gear = 5;
  inline bool has_gear() const;
  inline void clear_gear();
  static const int kGearFieldNumber = 5;
  inline ::google::protobuf::int32 gear() const;
  inline void set_gear(::google::protobuf::int32 value);

  // required int32 effectId = 6;
  inline bool has_effectid() const;
  inline void clear_effectid();
  static const int kEffectIdFieldNumber = 6;
  inline ::google::protobuf::int32 effectid() const;
  inline void set_effectid(::google::protobuf::int32 value);

  // repeated string effect = 7;
  inline int effect_size() const;
  inline void clear_effect();
  static const int kEffectFieldNumber = 7;
  inline const ::std::string& effect(int index) const;
  inline ::std::string* mutable_effect(int index);
  inline void set_effect(int index, const ::std::string& value);
  inline void set_effect(int index, const char* value);
  inline void set_effect(int index, const char* value, size_t size);
  inline ::std::string* add_effect();
  inline void add_effect(const ::std::string& value);
  inline void add_effect(const char* value);
  inline void add_effect(const char* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& effect() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_effect();

  // @@protoc_insertion_point(class_scope:PBMsgHeroHouseList.PBMsgSkillActived)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_actived();
  inline void clear_has_actived();
  inline void set_has_lv();
  inline void clear_has_lv();
  inline void set_has_hero();
  inline void clear_has_hero();
  inline void set_has_gear();
  inline void clear_has_gear();
  inline void set_has_effectid();
  inline void clear_has_effectid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 id_;
  bool actived_;
  ::google::protobuf::int32 lv_;
  ::google::protobuf::int32 hero_;
  ::google::protobuf::int32 gear_;
  ::google::protobuf::int32 effectid_;
  ::google::protobuf::RepeatedPtrField< ::std::string> effect_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(7 + 31) / 32];

  friend void  protobuf_AddDesc_PBMsgHeroHouseList_2eproto();
  friend void protobuf_AssignDesc_PBMsgHeroHouseList_2eproto();
  friend void protobuf_ShutdownFile_PBMsgHeroHouseList_2eproto();

  void InitAsDefaultInstance();
  static PBMsgHeroHouseList_PBMsgSkillActived* default_instance_;
};
// -------------------------------------------------------------------

class PBMsgHeroHouseList_PBMsgHero : public ::google::protobuf::Message {
 public:
  PBMsgHeroHouseList_PBMsgHero();
  virtual ~PBMsgHeroHouseList_PBMsgHero();

  PBMsgHeroHouseList_PBMsgHero(const PBMsgHeroHouseList_PBMsgHero& from);

  inline PBMsgHeroHouseList_PBMsgHero& operator=(const PBMsgHeroHouseList_PBMsgHero& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PBMsgHeroHouseList_PBMsgHero& default_instance();

  void Swap(PBMsgHeroHouseList_PBMsgHero* other);

  // implements Message ----------------------------------------------

  PBMsgHeroHouseList_PBMsgHero* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PBMsgHeroHouseList_PBMsgHero& from);
  void MergeFrom(const PBMsgHeroHouseList_PBMsgHero& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int64 userHeroId = 1;
  inline bool has_userheroid() const;
  inline void clear_userheroid();
  static const int kUserHeroIdFieldNumber = 1;
  inline ::google::protobuf::int64 userheroid() const;
  inline void set_userheroid(::google::protobuf::int64 value);

  // required .PBMsgHeroHouseList.PBMsgHeroStatus status = 2;
  inline bool has_status() const;
  inline void clear_status();
  static const int kStatusFieldNumber = 2;
  inline ::PBMsgHeroHouseList_PBMsgHeroStatus status() const;
  inline void set_status(::PBMsgHeroHouseList_PBMsgHeroStatus value);

  // required int32 heroId = 3;
  inline bool has_heroid() const;
  inline void clear_heroid();
  static const int kHeroIdFieldNumber = 3;
  inline ::google::protobuf::int32 heroid() const;
  inline void set_heroid(::google::protobuf::int32 value);

  // required int32 level = 4;
  inline bool has_level() const;
  inline void clear_level();
  static const int kLevelFieldNumber = 4;
  inline ::google::protobuf::int32 level() const;
  inline void set_level(::google::protobuf::int32 value);

  // required int32 renown = 5;
  inline bool has_renown() const;
  inline void clear_renown();
  static const int kRenownFieldNumber = 5;
  inline ::google::protobuf::int32 renown() const;
  inline void set_renown(::google::protobuf::int32 value);

  // required int32 nextRenown = 6;
  inline bool has_nextrenown() const;
  inline void clear_nextrenown();
  static const int kNextRenownFieldNumber = 6;
  inline ::google::protobuf::int32 nextrenown() const;
  inline void set_nextrenown(::google::protobuf::int32 value);

  // required int32 attack = 7;
  inline bool has_attack() const;
  inline void clear_attack();
  static const int kAttackFieldNumber = 7;
  inline ::google::protobuf::int32 attack() const;
  inline void set_attack(::google::protobuf::int32 value);

  // required int32 hp = 8;
  inline bool has_hp() const;
  inline void clear_hp();
  static const int kHpFieldNumber = 8;
  inline ::google::protobuf::int32 hp() const;
  inline void set_hp(::google::protobuf::int32 value);

  // required int32 load = 9;
  inline bool has_load() const;
  inline void clear_load();
  static const int kLoadFieldNumber = 9;
  inline ::google::protobuf::int32 load() const;
  inline void set_load(::google::protobuf::int32 value);

  // repeated .PBMsgHeroHouseList.PBMsgSkillActived skill = 10;
  inline int skill_size() const;
  inline void clear_skill();
  static const int kSkillFieldNumber = 10;
  inline const ::PBMsgHeroHouseList_PBMsgSkillActived& skill(int index) const;
  inline ::PBMsgHeroHouseList_PBMsgSkillActived* mutable_skill(int index);
  inline ::PBMsgHeroHouseList_PBMsgSkillActived* add_skill();
  inline const ::google::protobuf::RepeatedPtrField< ::PBMsgHeroHouseList_PBMsgSkillActived >&
      skill() const;
  inline ::google::protobuf::RepeatedPtrField< ::PBMsgHeroHouseList_PBMsgSkillActived >*
      mutable_skill();

  // repeated .PBMsgHeroHouseList.PBMsgSkillActived fate = 11;
  inline int fate_size() const;
  inline void clear_fate();
  static const int kFateFieldNumber = 11;
  inline const ::PBMsgHeroHouseList_PBMsgSkillActived& fate(int index) const;
  inline ::PBMsgHeroHouseList_PBMsgSkillActived* mutable_fate(int index);
  inline ::PBMsgHeroHouseList_PBMsgSkillActived* add_fate();
  inline const ::google::protobuf::RepeatedPtrField< ::PBMsgHeroHouseList_PBMsgSkillActived >&
      fate() const;
  inline ::google::protobuf::RepeatedPtrField< ::PBMsgHeroHouseList_PBMsgSkillActived >*
      mutable_fate();

  // required int32 might = 12;
  inline bool has_might() const;
  inline void clear_might();
  static const int kMightFieldNumber = 12;
  inline ::google::protobuf::int32 might() const;
  inline void set_might(::google::protobuf::int32 value);

  // required int32 maxExplore = 13;
  inline bool has_maxexplore() const;
  inline void clear_maxexplore();
  static const int kMaxExploreFieldNumber = 13;
  inline ::google::protobuf::int32 maxexplore() const;
  inline void set_maxexplore(::google::protobuf::int32 value);

  // required int32 explored = 14;
  inline bool has_explored() const;
  inline void clear_explored();
  static const int kExploredFieldNumber = 14;
  inline ::google::protobuf::int32 explored() const;
  inline void set_explored(::google::protobuf::int32 value);

  // required int32 sleepTime = 15;
  inline bool has_sleeptime() const;
  inline void clear_sleeptime();
  static const int kSleepTimeFieldNumber = 15;
  inline ::google::protobuf::int32 sleeptime() const;
  inline void set_sleeptime(::google::protobuf::int32 value);

  // required int32 cityIndex = 16;
  inline bool has_cityindex() const;
  inline void clear_cityindex();
  static const int kCityIndexFieldNumber = 16;
  inline ::google::protobuf::int32 cityindex() const;
  inline void set_cityindex(::google::protobuf::int32 value);

  // required int32 slot = 17;
  inline bool has_slot() const;
  inline void clear_slot();
  static const int kSlotFieldNumber = 17;
  inline ::google::protobuf::int32 slot() const;
  inline void set_slot(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:PBMsgHeroHouseList.PBMsgHero)
 private:
  inline void set_has_userheroid();
  inline void clear_has_userheroid();
  inline void set_has_status();
  inline void clear_has_status();
  inline void set_has_heroid();
  inline void clear_has_heroid();
  inline void set_has_level();
  inline void clear_has_level();
  inline void set_has_renown();
  inline void clear_has_renown();
  inline void set_has_nextrenown();
  inline void clear_has_nextrenown();
  inline void set_has_attack();
  inline void clear_has_attack();
  inline void set_has_hp();
  inline void clear_has_hp();
  inline void set_has_load();
  inline void clear_has_load();
  inline void set_has_might();
  inline void clear_has_might();
  inline void set_has_maxexplore();
  inline void clear_has_maxexplore();
  inline void set_has_explored();
  inline void clear_has_explored();
  inline void set_has_sleeptime();
  inline void clear_has_sleeptime();
  inline void set_has_cityindex();
  inline void clear_has_cityindex();
  inline void set_has_slot();
  inline void clear_has_slot();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int64 userheroid_;
  int status_;
  ::google::protobuf::int32 heroid_;
  ::google::protobuf::int32 level_;
  ::google::protobuf::int32 renown_;
  ::google::protobuf::int32 nextrenown_;
  ::google::protobuf::int32 attack_;
  ::google::protobuf::int32 hp_;
  ::google::protobuf::int32 load_;
  ::google::protobuf::RepeatedPtrField< ::PBMsgHeroHouseList_PBMsgSkillActived > skill_;
  ::google::protobuf::RepeatedPtrField< ::PBMsgHeroHouseList_PBMsgSkillActived > fate_;
  ::google::protobuf::int32 might_;
  ::google::protobuf::int32 maxexplore_;
  ::google::protobuf::int32 explored_;
  ::google::protobuf::int32 sleeptime_;
  ::google::protobuf::int32 cityindex_;
  ::google::protobuf::int32 slot_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(17 + 31) / 32];

  friend void  protobuf_AddDesc_PBMsgHeroHouseList_2eproto();
  friend void protobuf_AssignDesc_PBMsgHeroHouseList_2eproto();
  friend void protobuf_ShutdownFile_PBMsgHeroHouseList_2eproto();

  void InitAsDefaultInstance();
  static PBMsgHeroHouseList_PBMsgHero* default_instance_;
};
// -------------------------------------------------------------------

class PBMsgHeroHouseList : public ::google::protobuf::Message {
 public:
  PBMsgHeroHouseList();
  virtual ~PBMsgHeroHouseList();

  PBMsgHeroHouseList(const PBMsgHeroHouseList& from);

  inline PBMsgHeroHouseList& operator=(const PBMsgHeroHouseList& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PBMsgHeroHouseList& default_instance();

  void Swap(PBMsgHeroHouseList* other);

  // implements Message ----------------------------------------------

  PBMsgHeroHouseList* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PBMsgHeroHouseList& from);
  void MergeFrom(const PBMsgHeroHouseList& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef PBMsgHeroHouseList_PBMsgSkillActived PBMsgSkillActived;
  typedef PBMsgHeroHouseList_PBMsgHero PBMsgHero;

  typedef PBMsgHeroHouseList_PBMsgHeroStatus PBMsgHeroStatus;
  static const PBMsgHeroStatus UNLOCKED = PBMsgHeroHouseList_PBMsgHeroStatus_UNLOCKED;
  static const PBMsgHeroStatus IN_CITY_DO_NOTHING = PBMsgHeroHouseList_PBMsgHeroStatus_IN_CITY_DO_NOTHING;
  static const PBMsgHeroStatus IN_CITY_IN_MARCH = PBMsgHeroHouseList_PBMsgHeroStatus_IN_CITY_IN_MARCH;
  static const PBMsgHeroStatus IN_CITY_SLEEP = PBMsgHeroHouseList_PBMsgHeroStatus_IN_CITY_SLEEP;
  static const PBMsgHeroStatus IN_NO_CITY = PBMsgHeroHouseList_PBMsgHeroStatus_IN_NO_CITY;
  static inline bool PBMsgHeroStatus_IsValid(int value) {
    return PBMsgHeroHouseList_PBMsgHeroStatus_IsValid(value);
  }
  static const PBMsgHeroStatus PBMsgHeroStatus_MIN =
    PBMsgHeroHouseList_PBMsgHeroStatus_PBMsgHeroStatus_MIN;
  static const PBMsgHeroStatus PBMsgHeroStatus_MAX =
    PBMsgHeroHouseList_PBMsgHeroStatus_PBMsgHeroStatus_MAX;
  static const int PBMsgHeroStatus_ARRAYSIZE =
    PBMsgHeroHouseList_PBMsgHeroStatus_PBMsgHeroStatus_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  PBMsgHeroStatus_descriptor() {
    return PBMsgHeroHouseList_PBMsgHeroStatus_descriptor();
  }
  static inline const ::std::string& PBMsgHeroStatus_Name(PBMsgHeroStatus value) {
    return PBMsgHeroHouseList_PBMsgHeroStatus_Name(value);
  }
  static inline bool PBMsgHeroStatus_Parse(const ::std::string& name,
      PBMsgHeroStatus* value) {
    return PBMsgHeroHouseList_PBMsgHeroStatus_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // required int32 heroHouseSlots = 1;
  inline bool has_herohouseslots() const;
  inline void clear_herohouseslots();
  static const int kHeroHouseSlotsFieldNumber = 1;
  inline ::google::protobuf::int32 herohouseslots() const;
  inline void set_herohouseslots(::google::protobuf::int32 value);

  // required int32 opennedSlot = 2;
  inline bool has_opennedslot() const;
  inline void clear_opennedslot();
  static const int kOpennedSlotFieldNumber = 2;
  inline ::google::protobuf::int32 opennedslot() const;
  inline void set_opennedslot(::google::protobuf::int32 value);

  // repeated int32 unlockSlotDesc = 3;
  inline int unlockslotdesc_size() const;
  inline void clear_unlockslotdesc();
  static const int kUnlockSlotDescFieldNumber = 3;
  inline ::google::protobuf::int32 unlockslotdesc(int index) const;
  inline void set_unlockslotdesc(int index, ::google::protobuf::int32 value);
  inline void add_unlockslotdesc(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      unlockslotdesc() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_unlockslotdesc();

  // repeated .PBMsgHeroHouseList.PBMsgHero hero = 4;
  inline int hero_size() const;
  inline void clear_hero();
  static const int kHeroFieldNumber = 4;
  inline const ::PBMsgHeroHouseList_PBMsgHero& hero(int index) const;
  inline ::PBMsgHeroHouseList_PBMsgHero* mutable_hero(int index);
  inline ::PBMsgHeroHouseList_PBMsgHero* add_hero();
  inline const ::google::protobuf::RepeatedPtrField< ::PBMsgHeroHouseList_PBMsgHero >&
      hero() const;
  inline ::google::protobuf::RepeatedPtrField< ::PBMsgHeroHouseList_PBMsgHero >*
      mutable_hero();

  // @@protoc_insertion_point(class_scope:PBMsgHeroHouseList)
 private:
  inline void set_has_herohouseslots();
  inline void clear_has_herohouseslots();
  inline void set_has_opennedslot();
  inline void clear_has_opennedslot();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 herohouseslots_;
  ::google::protobuf::int32 opennedslot_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > unlockslotdesc_;
  ::google::protobuf::RepeatedPtrField< ::PBMsgHeroHouseList_PBMsgHero > hero_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];

  friend void  protobuf_AddDesc_PBMsgHeroHouseList_2eproto();
  friend void protobuf_AssignDesc_PBMsgHeroHouseList_2eproto();
  friend void protobuf_ShutdownFile_PBMsgHeroHouseList_2eproto();

  void InitAsDefaultInstance();
  static PBMsgHeroHouseList* default_instance_;
};
// ===================================================================


// ===================================================================

// PBMsgHeroHouseList_PBMsgSkillActived

// required int32 id = 1;
inline bool PBMsgHeroHouseList_PBMsgSkillActived::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PBMsgHeroHouseList_PBMsgSkillActived::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PBMsgHeroHouseList_PBMsgSkillActived::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PBMsgHeroHouseList_PBMsgSkillActived::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 PBMsgHeroHouseList_PBMsgSkillActived::id() const {
  return id_;
}
inline void PBMsgHeroHouseList_PBMsgSkillActived::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
}

// required bool actived = 2;
inline bool PBMsgHeroHouseList_PBMsgSkillActived::has_actived() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void PBMsgHeroHouseList_PBMsgSkillActived::set_has_actived() {
  _has_bits_[0] |= 0x00000002u;
}
inline void PBMsgHeroHouseList_PBMsgSkillActived::clear_has_actived() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void PBMsgHeroHouseList_PBMsgSkillActived::clear_actived() {
  actived_ = false;
  clear_has_actived();
}
inline bool PBMsgHeroHouseList_PBMsgSkillActived::actived() const {
  return actived_;
}
inline void PBMsgHeroHouseList_PBMsgSkillActived::set_actived(bool value) {
  set_has_actived();
  actived_ = value;
}

// optional int32 lv = 3;
inline bool PBMsgHeroHouseList_PBMsgSkillActived::has_lv() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void PBMsgHeroHouseList_PBMsgSkillActived::set_has_lv() {
  _has_bits_[0] |= 0x00000004u;
}
inline void PBMsgHeroHouseList_PBMsgSkillActived::clear_has_lv() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void PBMsgHeroHouseList_PBMsgSkillActived::clear_lv() {
  lv_ = 0;
  clear_has_lv();
}
inline ::google::protobuf::int32 PBMsgHeroHouseList_PBMsgSkillActived::lv() const {
  return lv_;
}
inline void PBMsgHeroHouseList_PBMsgSkillActived::set_lv(::google::protobuf::int32 value) {
  set_has_lv();
  lv_ = value;
}

// optional int32 hero = 4;
inline bool PBMsgHeroHouseList_PBMsgSkillActived::has_hero() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void PBMsgHeroHouseList_PBMsgSkillActived::set_has_hero() {
  _has_bits_[0] |= 0x00000008u;
}
inline void PBMsgHeroHouseList_PBMsgSkillActived::clear_has_hero() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void PBMsgHeroHouseList_PBMsgSkillActived::clear_hero() {
  hero_ = 0;
  clear_has_hero();
}
inline ::google::protobuf::int32 PBMsgHeroHouseList_PBMsgSkillActived::hero() const {
  return hero_;
}
inline void PBMsgHeroHouseList_PBMsgSkillActived::set_hero(::google::protobuf::int32 value) {
  set_has_hero();
  hero_ = value;
}

// optional int32 gear = 5;
inline bool PBMsgHeroHouseList_PBMsgSkillActived::has_gear() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void PBMsgHeroHouseList_PBMsgSkillActived::set_has_gear() {
  _has_bits_[0] |= 0x00000010u;
}
inline void PBMsgHeroHouseList_PBMsgSkillActived::clear_has_gear() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void PBMsgHeroHouseList_PBMsgSkillActived::clear_gear() {
  gear_ = 0;
  clear_has_gear();
}
inline ::google::protobuf::int32 PBMsgHeroHouseList_PBMsgSkillActived::gear() const {
  return gear_;
}
inline void PBMsgHeroHouseList_PBMsgSkillActived::set_gear(::google::protobuf::int32 value) {
  set_has_gear();
  gear_ = value;
}

// required int32 effectId = 6;
inline bool PBMsgHeroHouseList_PBMsgSkillActived::has_effectid() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void PBMsgHeroHouseList_PBMsgSkillActived::set_has_effectid() {
  _has_bits_[0] |= 0x00000020u;
}
inline void PBMsgHeroHouseList_PBMsgSkillActived::clear_has_effectid() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void PBMsgHeroHouseList_PBMsgSkillActived::clear_effectid() {
  effectid_ = 0;
  clear_has_effectid();
}
inline ::google::protobuf::int32 PBMsgHeroHouseList_PBMsgSkillActived::effectid() const {
  return effectid_;
}
inline void PBMsgHeroHouseList_PBMsgSkillActived::set_effectid(::google::protobuf::int32 value) {
  set_has_effectid();
  effectid_ = value;
}

// repeated string effect = 7;
inline int PBMsgHeroHouseList_PBMsgSkillActived::effect_size() const {
  return effect_.size();
}
inline void PBMsgHeroHouseList_PBMsgSkillActived::clear_effect() {
  effect_.Clear();
}
inline const ::std::string& PBMsgHeroHouseList_PBMsgSkillActived::effect(int index) const {
  return effect_.Get(index);
}
inline ::std::string* PBMsgHeroHouseList_PBMsgSkillActived::mutable_effect(int index) {
  return effect_.Mutable(index);
}
inline void PBMsgHeroHouseList_PBMsgSkillActived::set_effect(int index, const ::std::string& value) {
  effect_.Mutable(index)->assign(value);
}
inline void PBMsgHeroHouseList_PBMsgSkillActived::set_effect(int index, const char* value) {
  effect_.Mutable(index)->assign(value);
}
inline void PBMsgHeroHouseList_PBMsgSkillActived::set_effect(int index, const char* value, size_t size) {
  effect_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
}
inline ::std::string* PBMsgHeroHouseList_PBMsgSkillActived::add_effect() {
  return effect_.Add();
}
inline void PBMsgHeroHouseList_PBMsgSkillActived::add_effect(const ::std::string& value) {
  effect_.Add()->assign(value);
}
inline void PBMsgHeroHouseList_PBMsgSkillActived::add_effect(const char* value) {
  effect_.Add()->assign(value);
}
inline void PBMsgHeroHouseList_PBMsgSkillActived::add_effect(const char* value, size_t size) {
  effect_.Add()->assign(reinterpret_cast<const char*>(value), size);
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
PBMsgHeroHouseList_PBMsgSkillActived::effect() const {
  return effect_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
PBMsgHeroHouseList_PBMsgSkillActived::mutable_effect() {
  return &effect_;
}

// -------------------------------------------------------------------

// PBMsgHeroHouseList_PBMsgHero

// required int64 userHeroId = 1;
inline bool PBMsgHeroHouseList_PBMsgHero::has_userheroid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PBMsgHeroHouseList_PBMsgHero::set_has_userheroid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PBMsgHeroHouseList_PBMsgHero::clear_has_userheroid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PBMsgHeroHouseList_PBMsgHero::clear_userheroid() {
  userheroid_ = GOOGLE_LONGLONG(0);
  clear_has_userheroid();
}
inline ::google::protobuf::int64 PBMsgHeroHouseList_PBMsgHero::userheroid() const {
  return userheroid_;
}
inline void PBMsgHeroHouseList_PBMsgHero::set_userheroid(::google::protobuf::int64 value) {
  set_has_userheroid();
  userheroid_ = value;
}

// required .PBMsgHeroHouseList.PBMsgHeroStatus status = 2;
inline bool PBMsgHeroHouseList_PBMsgHero::has_status() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void PBMsgHeroHouseList_PBMsgHero::set_has_status() {
  _has_bits_[0] |= 0x00000002u;
}
inline void PBMsgHeroHouseList_PBMsgHero::clear_has_status() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void PBMsgHeroHouseList_PBMsgHero::clear_status() {
  status_ = 1;
  clear_has_status();
}
inline ::PBMsgHeroHouseList_PBMsgHeroStatus PBMsgHeroHouseList_PBMsgHero::status() const {
  return static_cast< ::PBMsgHeroHouseList_PBMsgHeroStatus >(status_);
}
inline void PBMsgHeroHouseList_PBMsgHero::set_status(::PBMsgHeroHouseList_PBMsgHeroStatus value) {
  assert(::PBMsgHeroHouseList_PBMsgHeroStatus_IsValid(value));
  set_has_status();
  status_ = value;
}

// required int32 heroId = 3;
inline bool PBMsgHeroHouseList_PBMsgHero::has_heroid() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void PBMsgHeroHouseList_PBMsgHero::set_has_heroid() {
  _has_bits_[0] |= 0x00000004u;
}
inline void PBMsgHeroHouseList_PBMsgHero::clear_has_heroid() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void PBMsgHeroHouseList_PBMsgHero::clear_heroid() {
  heroid_ = 0;
  clear_has_heroid();
}
inline ::google::protobuf::int32 PBMsgHeroHouseList_PBMsgHero::heroid() const {
  return heroid_;
}
inline void PBMsgHeroHouseList_PBMsgHero::set_heroid(::google::protobuf::int32 value) {
  set_has_heroid();
  heroid_ = value;
}

// required int32 level = 4;
inline bool PBMsgHeroHouseList_PBMsgHero::has_level() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void PBMsgHeroHouseList_PBMsgHero::set_has_level() {
  _has_bits_[0] |= 0x00000008u;
}
inline void PBMsgHeroHouseList_PBMsgHero::clear_has_level() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void PBMsgHeroHouseList_PBMsgHero::clear_level() {
  level_ = 0;
  clear_has_level();
}
inline ::google::protobuf::int32 PBMsgHeroHouseList_PBMsgHero::level() const {
  return level_;
}
inline void PBMsgHeroHouseList_PBMsgHero::set_level(::google::protobuf::int32 value) {
  set_has_level();
  level_ = value;
}

// required int32 renown = 5;
inline bool PBMsgHeroHouseList_PBMsgHero::has_renown() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void PBMsgHeroHouseList_PBMsgHero::set_has_renown() {
  _has_bits_[0] |= 0x00000010u;
}
inline void PBMsgHeroHouseList_PBMsgHero::clear_has_renown() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void PBMsgHeroHouseList_PBMsgHero::clear_renown() {
  renown_ = 0;
  clear_has_renown();
}
inline ::google::protobuf::int32 PBMsgHeroHouseList_PBMsgHero::renown() const {
  return renown_;
}
inline void PBMsgHeroHouseList_PBMsgHero::set_renown(::google::protobuf::int32 value) {
  set_has_renown();
  renown_ = value;
}

// required int32 nextRenown = 6;
inline bool PBMsgHeroHouseList_PBMsgHero::has_nextrenown() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void PBMsgHeroHouseList_PBMsgHero::set_has_nextrenown() {
  _has_bits_[0] |= 0x00000020u;
}
inline void PBMsgHeroHouseList_PBMsgHero::clear_has_nextrenown() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void PBMsgHeroHouseList_PBMsgHero::clear_nextrenown() {
  nextrenown_ = 0;
  clear_has_nextrenown();
}
inline ::google::protobuf::int32 PBMsgHeroHouseList_PBMsgHero::nextrenown() const {
  return nextrenown_;
}
inline void PBMsgHeroHouseList_PBMsgHero::set_nextrenown(::google::protobuf::int32 value) {
  set_has_nextrenown();
  nextrenown_ = value;
}

// required int32 attack = 7;
inline bool PBMsgHeroHouseList_PBMsgHero::has_attack() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void PBMsgHeroHouseList_PBMsgHero::set_has_attack() {
  _has_bits_[0] |= 0x00000040u;
}
inline void PBMsgHeroHouseList_PBMsgHero::clear_has_attack() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void PBMsgHeroHouseList_PBMsgHero::clear_attack() {
  attack_ = 0;
  clear_has_attack();
}
inline ::google::protobuf::int32 PBMsgHeroHouseList_PBMsgHero::attack() const {
  return attack_;
}
inline void PBMsgHeroHouseList_PBMsgHero::set_attack(::google::protobuf::int32 value) {
  set_has_attack();
  attack_ = value;
}

// required int32 hp = 8;
inline bool PBMsgHeroHouseList_PBMsgHero::has_hp() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void PBMsgHeroHouseList_PBMsgHero::set_has_hp() {
  _has_bits_[0] |= 0x00000080u;
}
inline void PBMsgHeroHouseList_PBMsgHero::clear_has_hp() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void PBMsgHeroHouseList_PBMsgHero::clear_hp() {
  hp_ = 0;
  clear_has_hp();
}
inline ::google::protobuf::int32 PBMsgHeroHouseList_PBMsgHero::hp() const {
  return hp_;
}
inline void PBMsgHeroHouseList_PBMsgHero::set_hp(::google::protobuf::int32 value) {
  set_has_hp();
  hp_ = value;
}

// required int32 load = 9;
inline bool PBMsgHeroHouseList_PBMsgHero::has_load() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void PBMsgHeroHouseList_PBMsgHero::set_has_load() {
  _has_bits_[0] |= 0x00000100u;
}
inline void PBMsgHeroHouseList_PBMsgHero::clear_has_load() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void PBMsgHeroHouseList_PBMsgHero::clear_load() {
  load_ = 0;
  clear_has_load();
}
inline ::google::protobuf::int32 PBMsgHeroHouseList_PBMsgHero::load() const {
  return load_;
}
inline void PBMsgHeroHouseList_PBMsgHero::set_load(::google::protobuf::int32 value) {
  set_has_load();
  load_ = value;
}

// repeated .PBMsgHeroHouseList.PBMsgSkillActived skill = 10;
inline int PBMsgHeroHouseList_PBMsgHero::skill_size() const {
  return skill_.size();
}
inline void PBMsgHeroHouseList_PBMsgHero::clear_skill() {
  skill_.Clear();
}
inline const ::PBMsgHeroHouseList_PBMsgSkillActived& PBMsgHeroHouseList_PBMsgHero::skill(int index) const {
  return skill_.Get(index);
}
inline ::PBMsgHeroHouseList_PBMsgSkillActived* PBMsgHeroHouseList_PBMsgHero::mutable_skill(int index) {
  return skill_.Mutable(index);
}
inline ::PBMsgHeroHouseList_PBMsgSkillActived* PBMsgHeroHouseList_PBMsgHero::add_skill() {
  return skill_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::PBMsgHeroHouseList_PBMsgSkillActived >&
PBMsgHeroHouseList_PBMsgHero::skill() const {
  return skill_;
}
inline ::google::protobuf::RepeatedPtrField< ::PBMsgHeroHouseList_PBMsgSkillActived >*
PBMsgHeroHouseList_PBMsgHero::mutable_skill() {
  return &skill_;
}

// repeated .PBMsgHeroHouseList.PBMsgSkillActived fate = 11;
inline int PBMsgHeroHouseList_PBMsgHero::fate_size() const {
  return fate_.size();
}
inline void PBMsgHeroHouseList_PBMsgHero::clear_fate() {
  fate_.Clear();
}
inline const ::PBMsgHeroHouseList_PBMsgSkillActived& PBMsgHeroHouseList_PBMsgHero::fate(int index) const {
  return fate_.Get(index);
}
inline ::PBMsgHeroHouseList_PBMsgSkillActived* PBMsgHeroHouseList_PBMsgHero::mutable_fate(int index) {
  return fate_.Mutable(index);
}
inline ::PBMsgHeroHouseList_PBMsgSkillActived* PBMsgHeroHouseList_PBMsgHero::add_fate() {
  return fate_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::PBMsgHeroHouseList_PBMsgSkillActived >&
PBMsgHeroHouseList_PBMsgHero::fate() const {
  return fate_;
}
inline ::google::protobuf::RepeatedPtrField< ::PBMsgHeroHouseList_PBMsgSkillActived >*
PBMsgHeroHouseList_PBMsgHero::mutable_fate() {
  return &fate_;
}

// required int32 might = 12;
inline bool PBMsgHeroHouseList_PBMsgHero::has_might() const {
  return (_has_bits_[0] & 0x00000800u) != 0;
}
inline void PBMsgHeroHouseList_PBMsgHero::set_has_might() {
  _has_bits_[0] |= 0x00000800u;
}
inline void PBMsgHeroHouseList_PBMsgHero::clear_has_might() {
  _has_bits_[0] &= ~0x00000800u;
}
inline void PBMsgHeroHouseList_PBMsgHero::clear_might() {
  might_ = 0;
  clear_has_might();
}
inline ::google::protobuf::int32 PBMsgHeroHouseList_PBMsgHero::might() const {
  return might_;
}
inline void PBMsgHeroHouseList_PBMsgHero::set_might(::google::protobuf::int32 value) {
  set_has_might();
  might_ = value;
}

// required int32 maxExplore = 13;
inline bool PBMsgHeroHouseList_PBMsgHero::has_maxexplore() const {
  return (_has_bits_[0] & 0x00001000u) != 0;
}
inline void PBMsgHeroHouseList_PBMsgHero::set_has_maxexplore() {
  _has_bits_[0] |= 0x00001000u;
}
inline void PBMsgHeroHouseList_PBMsgHero::clear_has_maxexplore() {
  _has_bits_[0] &= ~0x00001000u;
}
inline void PBMsgHeroHouseList_PBMsgHero::clear_maxexplore() {
  maxexplore_ = 0;
  clear_has_maxexplore();
}
inline ::google::protobuf::int32 PBMsgHeroHouseList_PBMsgHero::maxexplore() const {
  return maxexplore_;
}
inline void PBMsgHeroHouseList_PBMsgHero::set_maxexplore(::google::protobuf::int32 value) {
  set_has_maxexplore();
  maxexplore_ = value;
}

// required int32 explored = 14;
inline bool PBMsgHeroHouseList_PBMsgHero::has_explored() const {
  return (_has_bits_[0] & 0x00002000u) != 0;
}
inline void PBMsgHeroHouseList_PBMsgHero::set_has_explored() {
  _has_bits_[0] |= 0x00002000u;
}
inline void PBMsgHeroHouseList_PBMsgHero::clear_has_explored() {
  _has_bits_[0] &= ~0x00002000u;
}
inline void PBMsgHeroHouseList_PBMsgHero::clear_explored() {
  explored_ = 0;
  clear_has_explored();
}
inline ::google::protobuf::int32 PBMsgHeroHouseList_PBMsgHero::explored() const {
  return explored_;
}
inline void PBMsgHeroHouseList_PBMsgHero::set_explored(::google::protobuf::int32 value) {
  set_has_explored();
  explored_ = value;
}

// required int32 sleepTime = 15;
inline bool PBMsgHeroHouseList_PBMsgHero::has_sleeptime() const {
  return (_has_bits_[0] & 0x00004000u) != 0;
}
inline void PBMsgHeroHouseList_PBMsgHero::set_has_sleeptime() {
  _has_bits_[0] |= 0x00004000u;
}
inline void PBMsgHeroHouseList_PBMsgHero::clear_has_sleeptime() {
  _has_bits_[0] &= ~0x00004000u;
}
inline void PBMsgHeroHouseList_PBMsgHero::clear_sleeptime() {
  sleeptime_ = 0;
  clear_has_sleeptime();
}
inline ::google::protobuf::int32 PBMsgHeroHouseList_PBMsgHero::sleeptime() const {
  return sleeptime_;
}
inline void PBMsgHeroHouseList_PBMsgHero::set_sleeptime(::google::protobuf::int32 value) {
  set_has_sleeptime();
  sleeptime_ = value;
}

// required int32 cityIndex = 16;
inline bool PBMsgHeroHouseList_PBMsgHero::has_cityindex() const {
  return (_has_bits_[0] & 0x00008000u) != 0;
}
inline void PBMsgHeroHouseList_PBMsgHero::set_has_cityindex() {
  _has_bits_[0] |= 0x00008000u;
}
inline void PBMsgHeroHouseList_PBMsgHero::clear_has_cityindex() {
  _has_bits_[0] &= ~0x00008000u;
}
inline void PBMsgHeroHouseList_PBMsgHero::clear_cityindex() {
  cityindex_ = 0;
  clear_has_cityindex();
}
inline ::google::protobuf::int32 PBMsgHeroHouseList_PBMsgHero::cityindex() const {
  return cityindex_;
}
inline void PBMsgHeroHouseList_PBMsgHero::set_cityindex(::google::protobuf::int32 value) {
  set_has_cityindex();
  cityindex_ = value;
}

// required int32 slot = 17;
inline bool PBMsgHeroHouseList_PBMsgHero::has_slot() const {
  return (_has_bits_[0] & 0x00010000u) != 0;
}
inline void PBMsgHeroHouseList_PBMsgHero::set_has_slot() {
  _has_bits_[0] |= 0x00010000u;
}
inline void PBMsgHeroHouseList_PBMsgHero::clear_has_slot() {
  _has_bits_[0] &= ~0x00010000u;
}
inline void PBMsgHeroHouseList_PBMsgHero::clear_slot() {
  slot_ = 0;
  clear_has_slot();
}
inline ::google::protobuf::int32 PBMsgHeroHouseList_PBMsgHero::slot() const {
  return slot_;
}
inline void PBMsgHeroHouseList_PBMsgHero::set_slot(::google::protobuf::int32 value) {
  set_has_slot();
  slot_ = value;
}

// -------------------------------------------------------------------

// PBMsgHeroHouseList

// required int32 heroHouseSlots = 1;
inline bool PBMsgHeroHouseList::has_herohouseslots() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PBMsgHeroHouseList::set_has_herohouseslots() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PBMsgHeroHouseList::clear_has_herohouseslots() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PBMsgHeroHouseList::clear_herohouseslots() {
  herohouseslots_ = 0;
  clear_has_herohouseslots();
}
inline ::google::protobuf::int32 PBMsgHeroHouseList::herohouseslots() const {
  return herohouseslots_;
}
inline void PBMsgHeroHouseList::set_herohouseslots(::google::protobuf::int32 value) {
  set_has_herohouseslots();
  herohouseslots_ = value;
}

// required int32 opennedSlot = 2;
inline bool PBMsgHeroHouseList::has_opennedslot() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void PBMsgHeroHouseList::set_has_opennedslot() {
  _has_bits_[0] |= 0x00000002u;
}
inline void PBMsgHeroHouseList::clear_has_opennedslot() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void PBMsgHeroHouseList::clear_opennedslot() {
  opennedslot_ = 0;
  clear_has_opennedslot();
}
inline ::google::protobuf::int32 PBMsgHeroHouseList::opennedslot() const {
  return opennedslot_;
}
inline void PBMsgHeroHouseList::set_opennedslot(::google::protobuf::int32 value) {
  set_has_opennedslot();
  opennedslot_ = value;
}

// repeated int32 unlockSlotDesc = 3;
inline int PBMsgHeroHouseList::unlockslotdesc_size() const {
  return unlockslotdesc_.size();
}
inline void PBMsgHeroHouseList::clear_unlockslotdesc() {
  unlockslotdesc_.Clear();
}
inline ::google::protobuf::int32 PBMsgHeroHouseList::unlockslotdesc(int index) const {
  return unlockslotdesc_.Get(index);
}
inline void PBMsgHeroHouseList::set_unlockslotdesc(int index, ::google::protobuf::int32 value) {
  unlockslotdesc_.Set(index, value);
}
inline void PBMsgHeroHouseList::add_unlockslotdesc(::google::protobuf::int32 value) {
  unlockslotdesc_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
PBMsgHeroHouseList::unlockslotdesc() const {
  return unlockslotdesc_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
PBMsgHeroHouseList::mutable_unlockslotdesc() {
  return &unlockslotdesc_;
}

// repeated .PBMsgHeroHouseList.PBMsgHero hero = 4;
inline int PBMsgHeroHouseList::hero_size() const {
  return hero_.size();
}
inline void PBMsgHeroHouseList::clear_hero() {
  hero_.Clear();
}
inline const ::PBMsgHeroHouseList_PBMsgHero& PBMsgHeroHouseList::hero(int index) const {
  return hero_.Get(index);
}
inline ::PBMsgHeroHouseList_PBMsgHero* PBMsgHeroHouseList::mutable_hero(int index) {
  return hero_.Mutable(index);
}
inline ::PBMsgHeroHouseList_PBMsgHero* PBMsgHeroHouseList::add_hero() {
  return hero_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::PBMsgHeroHouseList_PBMsgHero >&
PBMsgHeroHouseList::hero() const {
  return hero_;
}
inline ::google::protobuf::RepeatedPtrField< ::PBMsgHeroHouseList_PBMsgHero >*
PBMsgHeroHouseList::mutable_hero() {
  return &hero_;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::PBMsgHeroHouseList_PBMsgHeroStatus>() {
  return ::PBMsgHeroHouseList_PBMsgHeroStatus_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_PBMsgHeroHouseList_2eproto__INCLUDED
